In [8]:
import numpy as np

In [43]:
# Array cuyos valores, son todos el valor de 0
zeros = np.zeros((2,4)) #2 filas 4 columnas 
#a.shape
#a.size #Total de registros
#zeros.ndim#Numero de dimenciones

In [37]:
# Array cuyos valores, son todos el valor de 1
one = np.ones((2,3,4))

In [36]:
# Array cuyos valores, son todos el valor indicado como segundo parámetro de La función
number = np.full((2,4,3),8)

In [46]:
# Inicializacion del array utilizando una lista de Python
b = np.array([[1, 2, 3], [4, 5, 6]])

In [50]:
# Creación del array utilizando una función basada en rangos 
# (minimo, maximo, número elementos del array)
range_based = np.linspace(0,6, 10)

In [51]:
# Inicialización del array con valores aleatorios
rand = np.random.rand(2,4,6)

In [53]:
# Inicialización del array con valores aleatorios conforme a una distribución normal
dis_normal = np.random.randn(2,4)

In [64]:
bidimensional = np.array([[1,2,3], [4,5,6]])
#bidimensional[0:2, 2] # Acceder al tercer elemento de las dos primeras filas del Array

In [68]:
# Creación de un Array unidimensional inicializado con el rango de elementos 0-27
arr_in_range = np.arange(28)


In [72]:
# Cambiar Las dimensiones del Array y sus Longitudes
arr_in_range.shape = (7, 4)

In [78]:
# EL ejemplo anterior devuelve un nuevo Array que apunta a Los mismos datos.
# Importante: Modificaciones en un Array, modificaran el otro Array
arr_in_range2 = array1.reshape (4, 7)

In [82]:
arr_in_range[0, 3] = 20
print(arr_in_range)
arr_in_range2


[[ 0  1  2 20]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]


array([[ 0,  1,  2, 20,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27]])

In [83]:
# Desenvuelve el Array, devolviendo un nuevo Array de una sola dimension
# Importante: El nuevo array apunta a Los mismos datos
arr_in_range.ravel()

array([ 0,  1,  2, 20,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [ ]:
# Creación de dos Arrays unidimensionales
array1 = np.arange(2, 18, 2)
array2 = np.arange(8)
# Suma indice por indice 
arrayı + array2
# Resta
arrayı - array2
# Multiplicacion
arrayı * array2